### ISSUE TITLE
Move contributor documentation off main site

### ISSUE THREAD

**Issue by ddbeck** [mdn/content#10868]
Right now, MDN’s meta documentation, such as style guides, process docs, and templates are part of the main reader-facing site. This presents two main problems:

- For readers, meta documentation is essential off-topic to web development and pollutes the site search. It may also create confusion (e.g., a reader might find our JavaScript style docs and wrongly interpret it to be general JS style guidance, rather than site-specific).
- For authors, it’s difficult to find, create, and edit meta documentation. It’s not specifically searchable and it’s somewhat spread throughout the site (setting aside the documentation that’s in the repo’s README).

To fix these problems, @rumyra and I plan to move MDN’s contributor documentation such that it meets these requirements:

- Contributor docs deploy to a separate domain from the main MDN site (e.g., contribute.developer.mozilla.org)
- Contributor docs deploy are generated by a separate process from the main MDN site (i.e., when you’re working with meta documentation, you’ll know it)
- Contributor docs have a distinct information architecture from the main MDN site (i.e., when you’re reading meta documentation, you’ll know it)
- Existing contributor docs can redirect to the new meta docs

A small number of meta docs may remain on MDN, such as an about page or a page about how MDN is authored. These should be relevant to web developers in MDN’s main audience and provide a pathway to learning more via the contributor docs site.

### Tasks
- [ ] Set up placeholder site for build and deploy
- [ ] Copy existing MDN meta docs to a legacy section on new site (regardless of quality, etc.)
- [ ] Set up redirects from existing docs to new docs
- [ ] Delete old docs

**Comment by Rumyra** [comment]
\o/ I'm so happy about this @ddbeck :D
