### ISSUE TITLE
Missing HTTP header-specific pages (known)

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/content#1458]
@hamishwillee commented on [Mon Nov 09 2020](https://github.com/mdn/sprints/issues/3872)

## URL(s)

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS - broken link to "Downlink"
- https://developer.mozilla.org/en-US/docs/Glossary/Client_hints

## Details
There are many missing HTTP header pages - as linked from URLs above. In some cases there have paragraph docs, in others there is nothing. List from the main [Headers Page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers): 

- [x] ~~Accept-Push-Policy~~ (#36149)
- [ ] Accept-Signature (https://github.com/mdn/content/issues/37701)
- [x] Content-DPR (#6097)
- [x] ~~Last-Event-ID~~ (#31146)
- [x] Origin-Isolation: https://github.com/mdn/content/pull/37297
- [x] ~~Ping-To~~ (#31146)
- [x] ~~Push-Policy~~ (#36149) 
- [x] Refresh (https://github.com/mdn/content/issues/15340)
- [x] Report-To (https://github.com/mdn/content/pull/35331)
- [ ] Sec-CH-UA-Form-Factor (https://github.com/mdn/content/issues/34853)
- [x] ~~Sec-CH-UA-Prefers-Color-Scheme~~ (https://github.com/mdn/content/pull/34850)
- [x] ~~Sec-CH-UA-Prefers-Reduced-Motion~~ (https://github.com/mdn/content/pull/34850)
- [ ] Sec-CH-UA-WoW64 (https://github.com/mdn/content/issues/34853)
- [x] Sec-WebSocket-Key (https://github.com/mdn/content/issues/34852)
- [x] Sec-WebSocket-Extensions (https://github.com/mdn/content/issues/34852)
- [x] Sec-WebSocket-Protocol (https://github.com/mdn/content/issues/34852)
- [x] Sec-WebSocket-Version (https://github.com/mdn/content/issues/34852)
- [x] Service-Worker-Allowed (https://github.com/mdn/content/issues/34854)
- [ ] Signed-Headers (https://github.com/mdn/content/issues/37701)
- [ ] Signature (https://github.com/mdn/content/issues/37701)
- [x] Viewport-Width (#6097)
- [x] Width (#5784)
- [x] ~~X-Download-Options~~
- [x] ~~X-Firefox-Spdy~~ (#31146)
- [x] X-Permitted-Cross-Domain-Policies https://github.com/mdn/content/pull/37192
- [x] ~~X-Pingback~~ (#31146)
- [x] X-Powered-By (#36862)
- [x] ~~X-Requested-With~~ (#31146)
- [x] X-Robots-Tag (https://github.com/mdn/content/pull/37079)
- [x] X-UA-Compatible

**Comment by jpmedley** [comment]
@Elchi3 I think some of these are Google's creation, so I'm trying to get some help within Google. Can you point me to a header reference page that's up to date with regard to style and structure?

**Comment by Elchi3** [comment]
I believe https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data is something that I wrote relatively recently.

**Comment by jpmedley** [comment]
I'm taking:

- Viewport-Width
-  Width
-  Content-DPR

Will probably do more later.

**Comment by sideshowbarker** [comment]
See also https://github.com/mdn/content/issues/1506#issuecomment-763172127

**Comment by SphinxKnight** [comment]
Cross-linking https://github.com/mdn/content/issues/15340 here

**Comment by Josh-Cena** [comment]
The remaining links are:

- [Accept-Push-Policy Header Field](https://datatracker.ietf.org/doc/html/draft-ruellan-http-accept-push-policy-00), an internet draft that seems abandoned
  - Accept-Push-Policy
  - Push-Policy
- [Signed HTTP exchanges](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html), an internet draft that seems new and non-standard
  - Accept-Signature
  - Signature
  - Signed-Headers
- Origin-Isolation, have no idea what this is, maybe an obsolete origin isolation API?
- Non-standard headers
  - X-Permitted-Cross-Domain-Policies
  - X-Powered-By
  - X-Robots-Tag

Pinging @mdn/yari-content-http to decide what to do for each feature group: should we remove all mentions to it, remove the links only, or add pages? It's hard to tell which ones are supported and to what extent.

**Comment by hamishwillee** [comment]
> what to do for each feature group: should we remove all mentions to it, remove the links only, or add pages? It's hard to tell which ones are supported and to what extent.

I don't know what you mean by this question - what page and headings are you referring to (I had a quick scan of the issue, but it has been a long time since it was posted and I have lost context).

**Comment by Josh-Cena** [comment]
I meant strictly in the context of my post: I have a list containing four groups of headers. I wonder if, for each group of headers, we should document them or not.

**Comment by hamishwillee** [comment]
For some reason, I'm not in that group. I've asked for access though. So here is "IMO":

I would drop [Accept-Push-Policy Header Field](https://datatracker.ietf.org/doc/html/draft-ruellan-http-accept-push-policy-02) as the policy is expired and archived. There is no evidence of implementation.

We should keep Signed HTTP Exchanges and document them. I don't know anything about them, but this spec is linked from https://developer.chrome.com/blog/signed-exchanges which indictates support from Chrome 73.

Remove `Origin-Isolation` - it isn't found in any search or present in the specs that to related to origin isolation.

**Comment by bsmth** [comment]
>  * [Accept-Push-Policy Header Field](https://datatracker.ietf.org/doc/html/draft-ruellan-http-accept-push-policy-00), an internet draft that seems abandoned 
>    * Accept-Push-Policy
>    * Push-Policy

I think we can cross these off the list as Server Push is being unshipped everywhere - https://groups.google.com/a/mozilla.org/g/dev-platform/c/vU9hJg343U8/m/4cZsHz7TAQAJ

**Comment by Josh-Cena** [comment]
@bsmth Is there a PR to remove references to these headers?

**Comment by bsmth** [comment]
> @bsmth Is there a PR to remove references to these headers?

I can remove in the following:

- [ ] https://github.com/mdn/content/pull/36149

**Comment by bsmth** [comment]
For signed exchanges, some info here:

- https://github.com/WICG/webpackage?tab=readme-ov-file#specifications
- Blogs:
  - https://web.dev/articles/signed-exchanges
  - https://developers.google.com/search/docs/appearance/signed-exchange
  - https://developers.cloudflare.com/speed/optimization/other/signed-exchanges/

**Comment by Josh-Cena** [comment]
Closing because all headers now have their specific issues
