### ISSUE TITLE
[CSP] wasm-unsafe-eval directive

### ISSUE THREAD

**Issue by evilpie** [mdn/content#17619]
This is a new CSP directive keyword similar to the existing `unsafe-eval`. We added this to Firefox release notes already becomes pages using WebAssembly with a strict CSP might break, because WASM is now blocked.

## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [ ] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
or
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

The new directive. At least on:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources

Maybe mention the impact on various WebAssembly APIs like
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compile
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compileStreaming
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module/Module

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1740263

## Tasks
 
- [x] WebExtensions relnote #16943.
- [x] Content & Fx relnote: https://github.com/mdn/content/pull/20485
- [ ] BCD: https://github.com/mdn/browser-compat-data/pull/17947

**Comment by 0526864223382** [comment]
> Esta es una nueva palabra clave de la directiva CSP similar a la existente ``inservible`.` Agregamos esto a las notas de la versión de Firefox ya que las páginas que usan Asamblea con un CSP estricto podrían romperse porque WASM ahora está bloqueado.
> 
> ## Criterios de aceptación
> * [ ] Las características enumeradas están suficientemente documentadas en MDN
> * [ ] BCD está actualizado
> * [ ] El ejemplo interactivo y los repositorios de datos se actualizan si corresponde
> * [ ] El contenido ha sido revisado según sea necesario.
> 
> ### Para la gente que ayuda con la documentación relacionada con Firefox
> * [ ] Establecer errores en`dev-doc-complete`
> * [ ] Agregue una entrada a las notas de la versión de Firefox si la característica está habilitada en la versión 
>   o
> * [ ] Agregue una entrada a la página de funciones experimentales de Firefox si la función aún no está habilitada en la versión
> 
> ## Características a documentar
> La nueva directiva. Al menos en:
> 
> * https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
> * https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
> * https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/Sources
> 
> Tal vez mencionar el impacto en varias API de WebAssembly como
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compile
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/compileStreaming
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Module/Module
> 
> ## Bichos Gecko relacionados
> https://bugzilla.mozilla.org/show_bug.cgi?id=1740263
> 
> ## Otro
> #16943 documentación agregada para esta característica en relación con WebExtensions únicamente.

#

**Comment by Rumyra** [comment]
I'm going to close this and chase up the bcd separately 👍
