### ISSUE TITLE
[HTML] `maction` / `semantics` elements behave as an `mrow` with the first child visible

### ISSUE THREAD

**Issue by bsmth** [mdn/content#20919]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1588733

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

### Tasks

- [x] Relnote https://github.com/mdn/content/pull/21627
- [x] content: https://github.com/mdn/content/commit/0fb5d5d5579d459f58ab52d0e6e94fc4634a9fe0
- [x] BCD: https://github.com/mdn/browser-compat-data/pull/17927

**Comment by bsmth** [comment]
Hi @fred-wang, I'm taking a look through this issue to see what's left to be documented. 

Does https://github.com/mdn/content/commit/0fb5d5d5579d459f58ab52d0e6e94fc4634a9fe0 cover the MDN/content side?

I see from the bugzilla bug that a release note needs to be added for Fx 106.

Is there anything else outstanding I can assist with?

**Comment by fred-wang** [comment]
Hi. I believed updates have been done incrementally in several PRs. The relevant parts for "The listed features are documented sufficiently on MDN" are:

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics
"By default, only the first child of the `<semantics>` element is rendered while the others have their display set to none."

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/maction
"By default, only the first child is rendered but some browsers may take into account actiontype and selection attributes to implement custom behaviors."

For "BCD is updated", this is shown on MDN:

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/maction#browser_compatibility
actiontype*  => removed in Firefox 106
selection => removed in Firefox 106

https://developer.mozilla.org/en-US/docs/Web/MathML/Element/semantics#browser_compatibility
"Use the algorithm described on MDN to determine the visible child." => removed in Firefox 106

"Interactive example and data repos are updated if appropriate": there are still examples on the MDN pages to show legacy behavior, and that's done on purpose. AFAIK, no other pages rely on the legacy behavior.

"The content has been reviewed as needed" => not sure what's expected here, but the github PRs followed the normal review process.

And for the section "Firefox related documentation" I guess we only need to add to the release note indeed.

**Comment by Rumyra** [comment]
Thanks both! @bsmth could we get `dev-doc-completed` on the bugzilla bug? Thanks!

**Comment by bsmth** [comment]
> Thanks both! @bsmth could we get `dev-doc-completed` on the bugzilla bug? Thanks!

Thanks for the reminder, done ✅

**Comment by Rumyra** [comment]
Awesome 🎉
