### ISSUE TITLE
[CSS] @supports `font-format()` and `font-tech()` functions 

### ISSUE THREAD

**Issue by bsmth** [mdn/content#20917]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Features to document

- https://developer.mozilla.org/en-US/docs/Web/CSS/@supports

`@supports` for CSS `font-format()` and `font-tech()` functions 

## Related Gecko bugs

- https://bugzilla.mozilla.org/show_bug.cgi?id=1786493

## Related issues

- https://github.com/w3c/csswg-drafts/issues/7633

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [ ] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

## Tasks

- [x] Content additions https://github.com/mdn/content/pull/21596
- [x] BCD https://github.com/mdn/browser-compat-data/pull/18034
- [x] Relnote https://github.com/mdn/content/pull/21626

**Comment by bsmth** [comment]
Related improvement follow-up could be `tech` attribute in `@font-face` under https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/src
