### ISSUE TITLE
[HTML] Add support for meta media (for meta name=theme-color)

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#20928]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [x] BCD is updated
- [ ] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [ ] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1706179

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if [Glossary](https://developer.mozilla.org/en-US/docs/Glossary) updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.

## Task tracking

- [x] BCD: https://github.com/mdn/browser-compat-data/pull/17995
- [x] Content: https://github.com/mdn/content/pull/21511
- [x] Minor cleanup https://github.com/mdn/content/pull/21456
- [x] Relnote: https://github.com/mdn/content/pull/21659

**Comment by bsmth** [comment]
There's an update in the Bugzilla bug about adding `HTMLMetaElement.media` to https://developer.mozilla.org/en-US/docs/Web/API/HTMLMetaElement. This can also be added to BCD

**Comment by bsmth** [comment]
Current updates here:

- [ ] Content: https://github.com/mdn/content/pull/21511

**Comment by Rumyra** [comment]
Thanks @bsmth 🎉
