### ISSUE TITLE
[HTML] Get rid of mozactionhint attribute

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#29312]
## Acceptance Criteria

- [x] The listed features are documented sufficiently on MDN
- [N/A] BCD is updated
- [N/A] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes if feature is enabled in release
- [N/A] Add entry to Firefox experimental features page if feature is not yet enabled in release

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1735980

## Other

- [x] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.
- [x] Check if glossary updates are required for the feature you're documenting - whether an existing term needs to be updated or a new term should be added.
- [x] Check if BCD update means that content pages need to have experimental markup removed or deprecated markup added (front matter tags and macros).

**Comment by zfox23** [comment]
## Todo
- [x] Understand what "get rid of" means in this context
    - It's useful to keep the documentation pertaining to `mozactionhint` where it exists, but it'd be great if it were clearer that the attribute should not be used.
    - There's an instance of `mozactionhint` in old FF release notes, and that should stay.
- [x] Add the pretty, inline `{{deprecated_inline}}` macro next to instances of `mozactionhint` throughout the content repository.
- [x] Ensure that the "deprecated" explanatory text is consistent across instances of `mozactionhint`.

## Associated PRs
https://github.com/mdn/content/pull/29469

**Comment by hamishwillee** [comment]
@dipikabh Should this be added as deprecated in BCD?
On one hand it may not seem worth it. But it might be because otherwise there is never going to be a trigger for us in 2 years to know that this needs to be removed altogether from docs.

**Comment by zfox23** [comment]
@hamishwillee From what I can see, `mozactionhint` isn't listed in the BCD at all right now. Are you suggesting adding a new row in the BCD for `mozactionhint`, marking it deprecated in FX, and marking it as unsupported in other browsers? Or something else?

**Comment by hamishwillee** [comment]
>Are you suggesting adding a new row in the BCD for mozactionhint, marking it deprecated in FX, and marking it as unsupported in other browsers? Or something else?

Almost. Yes, a new line in the BCD showing add/remove for FF, and not supported for other browsers. Feature non-standard and deprecated.

In about 2 years BCD would notice that nothing supports this feature and remove it - which would give us a trigger to actually clean the docs properly. Does that make sense?

**Comment by zfox23** [comment]
Yes, that makes sense! I'll open a new PR today, reference it here, and tag you.

**Comment by dipikabh** [comment]
> @dipikabh Should this be added as deprecated in BCD?
> otherwise there is never going to be a trigger for us in 2 years to know that this needs to be removed altogether from docs.

That is a good suggestion, @hamishwillee! I am wondering though how we decide to not add any of the other [non-standard attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#non-standard_attributes) to BCD

**Comment by hamishwillee** [comment]
@dipikabh I suspect it is a priority issue. BCD is supposed to include those, but much like you're unlikely to take the time to add a deprecated method if you happened to discover it, adding a non standard attribute is never going to be important as updating the standard attributes. Most of them were created pretty early in FireFox history - pretty rare to see a new one now days.

**Comment by dipikabh** [comment]
Makes sense, thanks, @hamishwillee.

Regarding `mozactionhint`, I guess we're still keeping a reference to it in our docs only for Firefox users because no other browser ever supported it.
