### ISSUE TITLE
Create function pages for easing functions

### ISSUE THREAD

**Issue by dipikabh** [mdn/content#29923]
**MDN URL**: https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function

**Related issue**: This is a follow-up to https://github.com/mdn/content/issues/20138.

**Context**: The `<easing-function>` data type page currently includes documentation for the `linear()`, `cubic-bezier()`, and `steps()` functions. As highlighted in this [review comment](https://github.com/mdn/content/pull/29585#pullrequestreview-1700789490), these functions should each have their dedicated pages.

**Tasks**:
- [x] Create a page for `linear()` function.
- [x] Create a page for `cubic-bezier()` function.
- [x] Create a page for `steps()` function.
- [x] Update `<easing-function>` page.
- [x] Update links for these functions in the [Easing functions](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Functions#easing_functions) section on the "CSS value functions" page.
