### ISSUE TITLE
Remove globals from Web/API

### ISSUE THREAD

**Issue by wbamberg** [mdn/content#33019]
This issue is to remove "globals" from Web/API, by instead having separate pages under `Window` and `WorkerGlobalScope`. This was discussed in https://github.com/orgs/mdn/discussions/360.

This has been done for `indexedDB` (https://github.com/mdn/content/pull/32040) and looks all right (https://github.com/orgs/mdn/discussions/360#discussioncomment-9023867), so let's do it for all the remaining pages.

- [x] [indexedDB](https://developer.mozilla.org/en-US/docs/Web/API/indexedDB)
- [x] [crypto](https://developer.mozilla.org/en-US/docs/Web/API/crypto_property)
- [x] [fetch](https://developer.mozilla.org/en-US/docs/Web/API/fetch)
- [x] [performance](https://developer.mozilla.org/en-US/docs/Web/API/performance_property)
- [x] [origin](https://developer.mozilla.org/en-US/docs/Web/API/origin)
- [x] [isSecureContext](https://developer.mozilla.org/en-US/docs/Web/API/isSecureContext)
- [x] [crossOriginIsolated](https://developer.mozilla.org/en-US/docs/Web/API/crossOriginIsolated)
- [x] [reportError](https://developer.mozilla.org/en-US/docs/Web/API/reportError)
- [x] [btoa](https://developer.mozilla.org/en-US/docs/Web/API/btoa)
- [x] [atob](https://developer.mozilla.org/en-US/docs/Web/API/atob)
- [x] [setTimeout](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout)
- [x] [clearTimeout](https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout)
- [x] [setInterval](https://developer.mozilla.org/en-US/docs/Web/API/setInterval)
- [x] [clearInterval](https://developer.mozilla.org/en-US/docs/Web/API/clearInterval)
- [x] [queueMicrotask](https://developer.mozilla.org/en-US/docs/Web/API/queueMicrotask)
- [x] [createImageBitmap](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap)
- [x] [structuredClone](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone)
- [x] [scheduler](https://developer.mozilla.org/en-US/docs/Web/API/scheduler_property)
- [x] [caches](https://developer.mozilla.org/en-US/docs/Web/API/caches)
- [x] [trustedTypes](https://developer.mozilla.org/en-US/docs/Web/API/trustedTypes)

For each page, the process is:

- yarn content move the global page to be under `Window`.
- update the page under `Window` to be an instance property or method page, and update the content accordingly
- create a new version of the page as an instance property or method page under `WorkerGlobalScope`, that's worker-specific
- manually delete the redirect from Web/API/WorkerGlobalScope/indexedDB to Web/API/indexedDB
- fix any domxref links so they don't incur redirects
- update GroupData, adding entries for the two new pages into the entry for the API that defines the feature (e.g. Indexed DB API).

*********************

Once all pages are fixed, the final step in this issue is to remove the `web-api-global-function` and `web-api-global-property` [page types](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types/Page_type_key#web_api_page_types).

- [ ] Remove global page types

**Comment by skyclouds2001** [comment]
Also, should the same thing to be done on BCD?

**Comment by wbamberg** [comment]
> Also, should the same thing to be done on BCD?

@Elchi3 , @queengooborg, wdyt?

**Comment by skyclouds2001** [comment]
seems https://github.com/mdn/browser-compat-data/issues/18739 is already discussing this issue
