### ISSUE TITLE
feat: complete `events.Event` docs

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/content#35359]
hopefully fixes #21523

```[tasklist]
### Tasks
- [ ] events.Event.addListener #35360
- [ ] events.Event.removeListener #35360
- [ ] events.Event.hasListener #35360
- [ ] events.Event.hasListeners #35360
- [ ] events.Event.addRules #35360
- [ ] events.Event.getRules #35360
- [ ] events.Event.removeRules #35360
```
