### ISSUE TITLE
[HTML] Implement the 'interactive-widget' meta viewport key

### ISSUE THREAD

**Issue by Rumyra** [mdn/content#35720]
## Acceptance criteria

- [x] The listed features are documented sufficiently on MDN
- [ ] BCD is updated
- [x] Interactive example and data repos are updated if appropriate
- [x] The content has been reviewed as needed

### For folks helping with Firefox related documentation

- [x] Set bugs to `dev-doc-complete`
- [x] Add entry to Firefox release notes for enabled/preview features
- [x] Add/remove entry to Firefox experimental features page for preference/released features

## Related Gecko bugs

https://bugzilla.mozilla.org/show_bug.cgi?id=1831649
https://bugzilla.mozilla.org/show_bug.cgi?id=1920755

## Other

- [ ] Check content open issues to see if any pertain to the subject matter. If there are any that can be closed because of the work, do so. If there are any that can be fixed relatively quickly because of the knowledge from completing this issue and you have time, feel free to go ahead and fix them.

**Comment by dletorey** [comment]
This has been fixed in Firefox 133 and I have tested it on:
- firefox nightly for android v133.0a1
- chrome for android v128.0.6613.146

**Comment by dletorey** [comment]
### Related issues and pull requests

- [Content PR](https://github.com/mdn/content/pull/37000)
- [Firefox release PR](https://github.com/mdn/content/pull/37001)
