### ISSUE TITLE
`{{XsltSidebar}}` omits some guides under `/web/xslt/`

### ISSUE THREAD

**Issue by bsmth** [mdn/content#37546]
The [addition of an XSLT Sidebar](https://github.com/mdn/yari/pull/9021/files) was intended to reproduce the minimal top-nav on these pages:

__previous nav:__

![image](https://github.com/mdn/content/assets/43580235/9f080dd7-0a2a-4c38-bdd6-6af972879626)

These nav elements look hand-picked and omit guides for space-saving reasons.

The new sidebar should include all pages under XPATH and XSLT, considering EXSLT and XML also.
```[tasklist]
### Tasks
- [x] Add XSLT guides to XsltSidebar macro
- [x] Remove usage of {{XSLTRef}} macro in content in favor of {{XsltSidebar}}
```

**Comment by bsmth** [comment]
This is now fixed in:

- [x] https://github.com/mdn/content/pull/37960
