### ISSUE TITLE
Javascript error reference is incomplete

### ISSUE THREAD

**Issue by nat-sch** [mdn/content#38439]
### Proposal

Hi! Looking through the error definitions in V8 and SpiderMonkey, I found errors that I couldn't find in the reference, and I think there could be a lot of them. Here are some examples:

| Code | Error (SpiderMonkey) |
| ---------|---------- |
| `Atomics.and()` | `TypeError: invalid array type for the operation`
| `class {}` | `SyntaxError: class statement requires a name`
| `(new WeakMap()).set('mykey', 1)` | `TypeError: WeakMap key "mykey" must be an object or an unregistered symbol`
| `Promise()` | `TypeError: calling a builtin Promise constructor without new is forbidden`
| `new Map([1,2])` | `TypeError: iterable for Map should have array-like object`
| `(class MyClass{})()` | `TypeError: class constructors must be invoked with 'new'`
| ``` `${``; ``` | `SyntaxError: missing } in template string`
|`/)/;` | `SyntaxError: unmatched ) in regular expression` 
| `Number({[Symbol.toPrimitive]: 1})` | `TypeError: can't convert ({[Symbol.toPrimitive]:1}) to number: its [Symbol.toPrimitive] property is not a function`
| `function test(...params, other){}` | `SyntaxError: parameter after rest parameter`
| `({set prop(){}})` | `SyntaxError: setter functions must have one argument`

One problem is that a lot of the errors in the engine's code I've looked at are not user facing, so I don't know how to give a definitive "this error is NEVER gonna appear in a web application", only "this error WILL appear, here's a code sample that throws it". The method I've been using to find undocumented errors is understanding or googling them and manually checking if I can cause them.

Maybe a good idea would be to keep a list of our progress through the engine's error definitions, or at least a list of the new errors we have found. If we base ourselves in an engine, we should agree which engine. Maybe SpiderMonkey would be a good choice.

Right now the Firefox's web console shows some JS errors with a link to their corresponding MDN docs article. After we document the new errors I'm proposing, we should probably notify the Firefox folks about it.

### Browser support

Yes, I've checked in Firefox 120.0 and Google Chrome 120.0.6099.129

### Tasks

- [ ] Look through error message definitions in a Javascript engine for user facing errors, modifying list/s to reflect our progress.
- [ ] Add a new article to the error reference for each undocumented error.
- [ ] Talk to the Firefox folks, to link the new docs in the Web Console errors.

### Dependencies

None

### Additional information

Here are some files I think we should be looking at:

- [SpiderMonkey error messages](https://github.com/mozilla/gecko-dev/blob/master/js/public/friend/ErrorNumbers.msg)
- [V8 error messages](https://github.com/v8/v8/blob/master/src/common/message-template.h)
- [Where I think Firefox maps erros to doc links](https://github.com/mozilla/gecko-dev/blob/master/devtools/server/actors/errordocs.js)

### Are you willing to support this work?

I can and want to support this work, with writing, reviews and feedback.

### Edits:

The lists we are using are:

[SpiderMonkey errors (more complete)](https://docs.google.com/spreadsheets/d/1BQRLHhNXvrTNKf6YkxdHVJ5eSjt9gM5-otmX9_jMKKM/edit?gid=0#gid=0)
[V8 errors](https://docs.google.com/spreadsheets/d/1uhg1jgB576rXVEHKLw3V2Kn-mG-SU6kfBHIi2b7brtE/edit#gid=0)

The intended workflow would be:
- Look at a very interesting line that is undocumented. We mostly trying to focus on those triaged as as "Common dev mistake".
- Put "claimed" in the PR cell, or the Note cell.
- When you have a PR sent, link it in the PR or Note cell, and mark the line as "documented". It's not necessary to wait for merging.

**Comment by Josh-Cena** [comment]
This project has run out of steam and is largely complete. The remaining ones are generally bad argument values or protocol violations which should be easily understood by the user. I may occasionally come back to the spreadsheets to keep things up to date, but I don't think we need to keep this issue open.
