### ISSUE TITLE
Add See also items for `selectionStart` and `selectionEnd`

### ISSUE THREAD

**Issue by nathnolt** [mdn/content#45314]
### Proposal

Right now there are no mentions of the properties selectionStart and selectionEnd, other than on the page https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/setSelectionRange

I think there should be a seperate page covering both selectionStart and selectionEnd. And that these properties should appear on both https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/text

I don't know if this is the correct form to mention this, but mdn pages report a bug wasn't correct, since I am proposing a new page / content.

### Task list

- [x] Create a new page for selectionStart and selectionEnd (or 2 seperate pages)
- [ ] Mention selectionStart and selectionEnd on Browser compatibility (figure out the browser compatibility) of both the textarea pages and the input pages (either just text, or also number, etc.) These would then be links, so you can click on them linking you to the page for selectionStart / selectionEnd

**Comment by bsmth** [comment]
Part of this is done here:

- [x] https://github.com/mdn/content/pull/35922

Looks like links to the API pages from the HTML elements is what's left.

**Comment by dipikabh** [comment]
Transferred this issue from mdn/mdn.

What's complete:
- via [#32202](https://github.com/mdn/content/pull/32202)
  - [`HTMLInputElement.selectionStart`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/selectionStart)
  - [`HTMLInputElement.selectionEnd`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/selectionEnd) 
- via [#35922](https://github.com/mdn/content/pull/35922)
  - [`HTMLTextAreaElement.selectionStart`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionStart)
  - [`HTMLTextAreaElement.selectionEnd`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLTextAreaElement/selectionEnd) 
- The compat data is available on the respective API pages, so no BCD changes needed

What's remaining:
- Link to these pages from [`<textarea>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/textarea) and [`<input type="text">`](https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/input/text)
- Add `<input>` and `HTMLInputElement` to the See also on the `HTMLInputElement.selectionStart` and `selectionEnd` pages
(to match the `HTMLTextAreaElement` see also counterparts)

**Comment by Josh-Cena** [comment]
We rarely ever link specific API properties from the HTML elements (and definitely not for the two elements in question) because the HTML reference documents HTML and not JS. There's a bogus "IDL attributes" in the input element pages' technical summary which ought to be removed. So the only remaining task is to add See also items for `HTMLInputElement.{selectionStart, selectionEnd}`.
