### ISSUE TITLE
WebXR guide material tracking issue

### ISSUE THREAD

**Issue by Elchi3** [mdn/content#7276]
(updated given Dominic's comment and more own thoughts)

Filing this bug to collect what kind of guide/tutorial content is missing in the WebXR docs. Planning to share this with subject matter experts and hopefully get some help with completing these pages

## Landing pages

- [ ] Brush up the [MDN graphics landing page](https://developer.mozilla.org/en-US/docs/Web/Guide/Graphics) to be more useful and to talk about WebXR
- [ ] Organize the [WebXR Device API](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API) landing page better (list the interfaces more efficiently, put more focus on the tutorials)

## Existing tutorials 

- [ ] [Fundamentals of WebXR](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Fundamentals) (to proof read to and get rid of "draft" banner)
- [ ] [WebXR application lifecycle](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Lifecycle) (to complete)
- [ ] [Starting up and shutting down a WebXR Session](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Startup_and_shutdown) (to proofread) 
- [ ] [Geometry and reference spaces in WebXR](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Geometry) (to proofread)
- [ ] [Spaces and reference spaces: Spatial tracking](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Spatial_tracking) (to proofread, to complete, to remove draft banner)
- [ ] [Rendering and the WebXR frame animation callback](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Rendering) (to proofread)
- [ ] [Viewpoints and viewers: Simulating cameras](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Cameras) (to proofread)
- [ ] [Lighting a WebXR setting](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Lighting) (to proofread and possible expand for Lighting Estimation module)
- [ ] [Using bounded reference spaces](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Bounded_reference_spaces) (to be completed, to proofread, to remove draft banner) 
- [ ] [Movement, orientation, and motion ](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Movement_and_motion)(to proofread)
- [ ] [Targeting and Hit detection](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Targeting) (to be completed, talk about Hit Testing Module)
- [ ] [WebXR performance guide](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Performance) (to be completed)
  -  Talk about foveate rendering (rendering more cheaply at lower resolution in the periphery of the view), refresh rates (there's [some documentation here](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Rendering#refresh_rate_and_frame_rate) but I don't think it covers requesting low and high refresh rates, [the refresh rate API,](https://github.com/immersive-web/webxr/issues/963) and what to do in practice to monitor and manage refresh rate), [multiview.](https://developer.mozilla.org/en-US/docs/Web/API/OVR_multiview2) 
- [ ] [WebXR permissions and security](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Permissions_and_security) (to complete; MDN still needs to document the Permission-Policy header, still documents this as Feature-Policy -> side project; talk about secure origin requirement)

## New tutorials to write
- [ ] Using WebXR input profiles. Cover Hands Input profile
- [ ] Gamecontroller (Gamepad API) in WebXR
- [ ] WebXR Layers / Playing video in a 3D environment
- [ ] First person observer / secondary views (https://github.com/mdn/content/pull/7153#issuecomment-885787729). Maybe integrate this aspect into the "Viewports and viewers" article?)
- [ ] Depth Information
- [ ] ~Positional audio in a 3D environment (not integrated into WebXR, address this topic later, remove from landing page)~

**Comment by dominiccooney** [comment]
Great list. Here's some feedback from Oculus:

Positional audio isn't integrated with WebXR (it probably should be) so maybe that is a topic to address last/later.

Playing video in a 3D environment is a good application of Layers, so it could be efficient to work on those together. The reason Layers are good for 3D video is that even if the page doesn't submit WebXR frames on time, the VR compositor can update the video texture so playback is smooth; and using a Layer means the video looks sharper because it is only sampled once, by the VR compositor, instead of once by the application to produce the scene and again by the VR compostor. This is not only good for low latency and visual quality, it is also more power efficient. Incidentally, we wrote a [Layers polyfill](https://github.com/immersive-web/webxr-layers-polyfill); should provide some ideas for supporting UAs which don't implement Layers.

There is kind of an "input" theme with input profiles, game controllers, targeting and hit detection. We would like to see coverage of the Hands input profile.

We see developers struggle with the secure origin requirement. Brief links to that in the tutorial content could be helpful.

Performance would be a good topic to cover. MDN has some great WebGL performance content. On top of that there's some WebXR specific aspects: Foveated rendering (rendering more cheaply at lower resolution in the periphery of the view), refresh rates (there's [some documentation here](https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Rendering#refresh_rate_and_frame_rate) but I don't think it covers requesting low and high refresh rates, [the refresh rate API,](https://github.com/immersive-web/webxr/issues/963) and what to do in practice to monitor and manage refresh rate), [multiview.](https://developer.mozilla.org/en-US/docs/Web/API/OVR_multiview2)

Footnote, isFirstPersonObserver is an interesting case... The compat table says this is supported in Chrome 86, but if you [look at the implementation](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/modules/xr/xr_view.h;l=47?q=isfirstpersonobserver&ss=chromium) it is unconditionally false. With my web developer hat on it would be useful to know that so I can manage my implementation effort. (I don't know what Samsung Internet's level of support for isFirstPersonObserver is.) From the Browser vendor's perspective the most important thing is authors render all of their views and don't hard code support for, say, just two views so that if first person observer views light up later sites won't break.

**Comment by Elchi3** [comment]
Another article could be about XR accessibility. See https://w3c.github.io/apa/xaur/

**Comment by dominiccooney** [comment]
WebXR Guides are particularly important. WebGL is very stateful and it is hard to inspect the state. Adding WebXR on top of that, where you don't precisely control your inputs like pose, sensed depth, etc. it can be very hard to understand if you're working from an API reference alone. Guides are important.

There's been great momentum on WebXR docs in Q3. We should capitalize on that.

**Comment by zenhairdo** [comment]
Get the fucking guy out of the fucking cuck caddy o7

**Comment by Josh-Cena** [comment]
I'm closing it in favor of https://github.com/openwebdocs/project/issues/158 because it doesn't look like there's any progress on this from the MDN team.
