### ISSUE TITLE
Content bug: /web References Have Short Shelf Life

### ISSUE THREAD

**Issue by jpmedley** [mdn/content#7586]
## What page(s) did you find the problem on?

Several years ago, Google built [web.dev](https://web.dev/) and [developer.chrome.com](https://developer.chrome.com/) as replacements for https://developers.google.com/web. We have been gradually republishing old articles on the new sites. References to this site should be replaced or removed. Where replacements exist, the old URLs redirect to the new ones. Eventually redirects will go away. I expect this will be a long-lived bug as it will take some time for Google to republish outstanding articles. 

(Ping me about the status of specific articles.)

- [x] .//files/en-us/mozilla/add-ons/webextensions/api/devtools/panels/elementspanel/createsidebarpane/index.html - Fixed #9911
- [x] .//files/en-us/learn/common_questions/what_are_browser_developer_tools/index.html
- [ ] .//files/en-us/learn/javascript/client-side_web_apis/client-side_storage/index.html (_[Link not migrated](https://developers.google.com/web/fundamentals/codelabs/offline/) 20211019_)
- [ ] .//files/en-us/learn/performance/web_performance_basics/index.html (_links not migrated 20211019_)
- [x] .//files/en-us/learn/tools_and_testing/cross_browser_testing/testing_strategies/index.html - Fixed #9911
- [x] .//files/en-us/learn/tools_and_testing/cross_browser_testing/javascript/index.html - Fixed #9911
- [ ] .//files/en-us/tools/about_colon_debugging/index.html (_links not migrated 20211019_)
- [ ] .//files/en-us/tools/about_colon_debugging/about_colon_debugging_before_firefox_68/index.html (_links not migrated 20211019_)
- [ ] .//files/en-us/plugins/flash_to_html5/video/drm_and_authentication/index.html (_links not migrated 20211019_)
- [ ] .//files/en-us/plugins/flash_to_html5/video/players/index.html (_links not migrated 20211019_)
- [x] .//files/en-us/plugins/flash_to_html5/video/file_format_conversion/index.html - Fixed #9911
- [ ] .//files/en-us/web/guide/performance/index.html (_links not migrated 20211019_)
- [x] .//files/en-us/web/css/scroll-margin-block-start/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-snap-points-y/index.html - Fixed by #7929
- [ ] .//files/en-us/web/css/overscroll-behavior-block/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/css/overscroll-behavior-inline/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/css/scroll-snap-points-x/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-top/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-top/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-right/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-right/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-block-end/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-snap-destination/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-left/index.html - Fixed by #7929
- [ ] .//files/en-us/web/css/overscroll-behavior/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/css/scroll-margin-block-end/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-snap-type/index.html - Fixed by #7929
- [ ] .//files/en-us/web/css/touch-action/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/css/scroll-snap-stop/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-left/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-block-start/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-inline-start/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-inline-start/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-inline-end/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-inline-end/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-inline/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-inline/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-block/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-bottom/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-padding-bottom/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-margin-block/index.html - Fixed by #7929
- [x] .//files/en-us/web/css/scroll-snap-align/index.html - Fixed by #7929
- [ ] .//files/en-us/web/css/overscroll-behavior-x/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/css/scroll-snap-coordinate/index.html - Fixed by #7929
- [ ] .//files/en-us/web/css/overscroll-behavior-y/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/security/secure_contexts/features_restricted_to_secure_contexts/index.html - *links not migrated 20211119*
- [ ] .//files/en-us/web/html/element/meta/name/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/html/element/meta/name/theme-color/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/html/link_types/preload/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/progressive_web_apps/index.html  - *link not migrated 20211119*
- [ ] .//files/en-us/web/progressive_web_apps/introduction/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/progressive_web_apps/add_to_home_screen/index.html - Fixed #10637
- [ ] .//files/en-us/web/progressive_web_apps/developer_guide/installing/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/http/headers/viewport-width/index.html  - *link not migrated 20210827*
- [ ] .//files/en-us/web/http/headers/width/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/save-data/index.html - (as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/rtt/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/dpr/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/ect/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/downlink/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/content-dpr/index.html - *(as above: link not migrated 20210827)*
- [ ] .//files/en-us/web/http/headers/device-memory/index.html - *(as above: link not migrated 20210827)*
- [x] .//files/en-us/web/http/caching/index.html Fixed by #7921
- [ ] .//files/en-us/web/http/feature_policy/index.html - FIXED (already)
- [ ] .//files/en-us/web/api/touchevent/index.html  - *link not migrated 20211119*
- [x] .//files/en-us/web/api/clients/claim/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/api/background_fetch_api/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/api/abortsignal/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/api/resize_observer_api/index.html - Fixed #10637
- [ ] .//files/en-us/web/api/reporting_api/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/api/indexeddb_api/browser_storage_limits_and_eviction_criteria/index.html - Fixed #10637
- [ ] .//files/en-us/web/api/worklet/index.html - *link not migrated 20211119*
- [x] .//files/en-us/web/api/long_tasks_api/index.html - Fixed by #10637
- [ ] .//files/en-us/web/api/interventionreportbody/index.html  - *link not migrated 20211119*
- [x] .//files/en-us/web/api/element/setattribute/index.html - Fixed by #10637
- [ ] .//files/en-us/web/api/document/write/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/api/document/createelementns/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/web/api/document/visibilitychange_event/index.html
- [ ] .//files/en-us/web/api/subtlecrypto/importkey/index.html
- [ ] .//files/en-us/web/api/subtlecrypto/exportkey/index.html
- [ ] .//files/en-us/web/api/push_api/index.html
- [ ] .//files/en-us/web/api/touch_events/using_touch_events/index.html
- [ ] .//files/en-us/web/api/fetchevent/preloadresponse/index.html
- [ ] .//files/en-us/web/api/window/pagehide_event/index.html
- [ ] .//files/en-us/web/api/window/unload_event/index.html
- [ ] .//files/en-us/web/api/window/beforeunload_event/index.html
- [ ] .//files/en-us/web/api/deprecationreportbody/index.html
- [ ] .//files/en-us/web/api/navigator/registerprotocolhandler/web-based_protocol_handlers/index.html
- [ ] .//files/en-us/web/api/navigator/sendbeacon/index.html
- [ ] .//files/en-us/web/api/htmlaudioelement/index.html
- [ ] .//files/en-us/web/api/urlsearchparams/index.html
- [ ] .//files/en-us/web/api/urlsearchparams/append/index.html
- [ ] .//files/en-us/web/api/urlsearchparams/tostring/index.html
- [ ] .//files/en-us/web/api/web_audio_api/using_audioworklet/index.html
- [ ] .//files/en-us/web/api/abortcontroller/index.html
- [ ] .//files/en-us/web/api/console/timestamp/index.html
- [ ] .//files/en-us/web/api/console/error/index.html
- [ ] .//files/en-us/web/javascript/guide/using_promises/index.md - (_Links not migrated 20201019_)
- [ ] .//files/en-us/web/javascript/guide/modules/index.md
- [ ] .//files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md
- [ ] .//files/en-us/web/javascript/reference/global_objects/intl/relativetimeformat/index.md
- [ ] .//files/en-us/web/javascript/reference/global_objects/intl/relativetimeformat/relativetimeformat/index.md
- [ ] .//files/en-us/web/performance/lazy_loading/index.html
- [ ] .//files/en-us/web/performance/performance_budgets/index.html
- [x] .//files/en-us/web/accessibility/seizure_disorders/index.html - Fixed #10637
- [x] .//files/en-us/web/media/autoplay_guide/index.html - Fixed by #7635
- [x] .//files/en-us/webassembly/index.html  - Fixed by #7635
- [ ] .//files/en-us/webassembly/existing_c_to_wasm/index.html - *link not migrated 20211119*
- [x] .//files/en-us/glossary/time_to_interactive/index.html - Fixed by #7635
- [x] .//files/en-us/glossary/progressive_web_apps/index.html - Fixed by #7635
- [ ] .//files/en-us/glossary/synthetic_monitoring/index.html - *link not migrated 20211119*
- [ ] .//files/en-us/glossary/first_interactive/index.html - *link not migrated 20211119*
- [x] .//files/en-us/games/techniques/audio_for_web_games/index.html - Fixed by #7635

**Comment by hamishwillee** [comment]
@peterbe FYI this is case where adding the HTTP status to the flaw checker/report on external links would make it easier to spot the redirects/work to be done.

**Comment by rachelandrew** [comment]
As part of the work I'm doing for Google, I'll migrate the scroll snap article that all of those scroll-related pages point to, so that will sort out a good chunk of them.

**Comment by peterbe** [comment]
> @peterbe FYI this is case where adding the HTTP status to the flaw checker/report on external links would make it easier to spot the redirects/work to be done.
I think it would be very feasible to do an external URLs check in the PR Review Companion. We're already carefully listing every single external URL there. I'll play with something and see how it feels.

**Comment by jpmedley** [comment]
I don't expect anyone else to help with this effort, but if you happen to be in one of those files and know that it contains a link that redirects, feel free to update it. I would be thankful. 

@rachelandrew I had in mind that we would check items off this list as we finish them.

**Comment by hamishwillee** [comment]
@MrBrain295 Fantastic job! Are all the cases in the checkboxes above now "done"?

**Comment by MrBrain295** [comment]
For the most part but a few links still need to be migrated to web.dev or developer.chrome.com.

**Comment by hamishwillee** [comment]
Thanks Gabe. If you're able to mark/check the ones that have been fixed that would be great. Unless we think this is a waste of time because you'd always just do a global search on developer.google.com if you were doing this kind of fix.

**Comment by MrBrain295** [comment]
@hamishwillee I don’t have the ability to check the boxes.

**Comment by hamishwillee** [comment]
No worries. Thanks for fixing all these cases!

**Comment by 20jasper** [comment]
I'm not sure if everything is up to date, but I just checked and web/api/clients/claim/index.html is already updated, and for en-us/web/performance/performance_budgets/index.html the link is not migrated yet

**Comment by hamishwillee** [comment]
Thanks @20jasper - I marked the first one as done.

**Comment by sideshowbarker** [comment]
> There is one remaining link ([here](https://github.com/mdn/content/blob/main/files/en-us/learn/performance/web_performance_basics/index.md?rgh-link-date=2022-06-29T16%3A00%3A27Z)) that is not fixed but all the others are done.

I guess that means the link to https://developers.google.com/web/tools/chrome-user-experience-report

That “Chrome User Experience Report” still seems useful and has no equivalent at https://web.dev/, so it would not seem beneficial to just remove the link. So we can keep it unless/until someone comments here with info otherwise.

And given that, I’m going ahead and closing this.

**Comment by rachelandrew** [comment]
@sideshowbarker I'm the person who has been doing the migration off developers.google.com. The Chrome User Experience docs are being migrated to developer.chrome.com.

The PR is here, so it should be there soon. https://github.com/GoogleChrome/developer.chrome.com/pull/3078

**Comment by sideshowbarker** [comment]
Hi @rachelandrew — thanks much, reopened here

**Comment by rachelandrew** [comment]
@sideshowbarker our docs are now live so I've created a PR to update that link: https://github.com/mdn/content/pull/18541
